import { readFile, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";

const registryUrl = new URL("../assets/color-themes.json", import.meta.url);
const materialUrl = new URL("../assets/material.css", import.meta.url);
const registry = JSON.parse(await readFile(registryUrl, "utf8"));
const ROLE_VARIABLES = Object.freeze({
  displayField: "primary", onDisplayField: "on-primary", displayHeading: "display-heading",
  surface: "surface", onSurface: "ink", coloredHeading: "heading", accent: "accent",
  onAccent: "on-accent", neutral: "canvas", onNeutral: "on-canvas", mutedNeutral: "canvas-muted",
  secondaryText: "muted", divider: "divider", tint: "tint", onTint: "on-tint",
  readingMarker: "reading-marker", emphasisText: "emphasis-text", coverAccent: "cover-accent",
  illustrationSurface: "illustration-surface",
});
const byId = new Map();
for (const theme of registry.themes) {
  if (!/^[A-Za-z0-9-]+$/.test(theme.id) || byId.has(theme.id)) throw new Error("Invalid or duplicate theme ID");
  if (!["light", "dark"].includes(theme.colorScheme)) throw new Error(`Invalid color scheme: ${theme.id}`);
  for (const role of Object.keys(ROLE_VARIABLES)) if (!/^#[0-9A-F]{6}$/.test(theme.roles[role])) throw new Error(`Invalid theme role: ${theme.id}.${role}`);
  Object.freeze(theme.roles);
  byId.set(theme.id, Object.freeze(theme));
}
for (const [alias, target] of Object.entries(registry.aliases)) {
  if (!/^[A-Za-z0-9-]+$/.test(alias) || byId.has(alias) || !byId.has(target)) throw new Error(`Invalid theme alias: ${alias}`);
}
export const THEME_IDS = Object.freeze([...byId.keys()]);
export function resolveTheme(value = "A") {
  const canonical = registry.aliases[value] ?? value;
  const theme = byId.get(canonical);
  if (!theme) throw new Error(`input.theme: expected ${THEME_IDS.join(", ")} (legacy aliases: B, C2)`);
  return theme;
}
export function themeCss() {
  return `/* BEGIN CALIBRATED THEMES — generated by scripts/color-themes.mjs; edit assets/color-themes.json */\n${registry.themes.map((theme) => {
    const aliases = Object.entries(registry.aliases).filter(([, target]) => target === theme.id).map(([alias]) => alias);
    const selectors = [theme.id, ...aliases].map((id) => `[data-theme="${id}"]`).join(", ");
    const vars = Object.entries(ROLE_VARIABLES).map(([role, variable]) => `  --${variable}: ${theme.roles[role]};`).join("\n");
    return `${selectors} {\n${vars}\n  color-scheme: ${theme.colorScheme};\n}`;
  }).join("\n")}\n/* END CALIBRATED THEMES */`;
}
export async function syncThemeCss({ check = false } = {}) {
  const css = await readFile(materialUrl, "utf8");
  const block = /\/\* BEGIN CALIBRATED THEMES[\s\S]*?\/\* END CALIBRATED THEMES \*\//;
  const next = block.test(css) ? css.replace(block, themeCss()) : `${css.trimEnd()}\n\n${themeCss()}\n`;
  if (check && css !== next) throw new Error("Calibrated theme CSS is stale; run node scripts/color-themes.mjs");
  if (!check && css !== next) await writeFile(materialUrl, next);
}
if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  syncThemeCss({ check: process.argv.includes("--check") }).then(() => console.log("Calibrated theme CSS is synchronized.")).catch((error) => { console.error(error.message); process.exitCode = 1; });
}
